
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
import tkinter as tk
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from DeleteDistributor import DeleteFrame
from Home import HomeFrame
from DistributorSearch import SearchFrame
from SearchResult import ResultFrame
from ComissionCalculator import CalculatorFrame

class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("MLM Management App")
        self.geometry("800x500")
        self.configure(bg = "#FFFFFF")
        #Initialize the frame
        self.home_frame = HomeFrame(self)
        self.home_frame.place(x=0, y=0)
        
        self.delete_frame = ""
        self.commision_frame = ""
        self.result_frame = ""

window=App()
window.resizable(False, False)
window.mainloop()